services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    networks:
      - appnet

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
      args:
        DOCKER_GID: 1001
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    container_name: app
    user: "${UID}:${GID}"
    group_add:
      - "1001"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./node:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
