FROM node:20.10

ARG USER_ID
ARG DOCKER_GID

ENV USER_NAME=appuser

# Check if the user already exists, if so, modify it, if not, create it
RUN if id -u $USER_ID >/dev/null 2>&1; then \
        existing_user=$(getent passwd $USER_ID | cut -d: -f1) && \
        usermod -l $USER_NAME $existing_user && \
        usermod -g $DOCKER_GID -d /home/$USER_NAME -m $USER_NAME; \
    else \
        useradd -u $USER_ID -g $DOCKER_GID -m -s /bin/bash $USER_NAME; \
    fi

WORKDIR /workspace

# Set Dockerize environment variable
ENV DOCKERIZE_VERSION v0.7.0

# Install docker
RUN apt-get update \
    && apt-get install -y curl \
    && curl -sSL https://get.docker.com/ | sh

# Install dockerize
RUN apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

USER $USER_NAME

# Execute dockerize to wait for the database to be fully initialized
ENTRYPOINT ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "docker-entrypoint.sh"]
