FROM node:20.10

WORKDIR /workspace

# Set Dockerize environment variable
ENV DOCKERIZE_VERSION v0.7.0

# Install dockerize
RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

# Execute dockerize to wait for the database to be fully initialized
ENTRYPOINT ["dockerize", "-wait", "tcp://db:3306", "docker-entrypoint.sh"]
